import Head from "next/head";
import React from "react";
import Navbar from "../../components/Navbar";

const Factory = () => {
  return (
    <div className="w-full">
      <Head>
        <title>Monitait - Factory</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Navbar />
    </div>
  );
};

export default Factory;
