import Head from "next/head";
import React from "react";
import Card from "../../components/Card";
import Content from "../../components/Content";
import Line from "../../components/Line";
import Navbar from "../../components/Navbar";

const Operators = () => {
  return (
    <div className="w-full flex flex-col">
      <Head>
        <title>Monitait - Factory</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Navbar />
      <Content>
        <div className="flex flex-col md:flex-row w-full justify-between">
          <Card date="Morning" startTime="7:00 AM" endTime="2:00 PM">
            <Line label="Line 1"></Line>
          </Card>
          <Card date="Afternoon" startTime="2:00 PM" endTime="9:00 PM">
            <div>
              <Line label="Line 1"></Line>
              <Line label="Line 2"></Line>
            </div>
          </Card>
          <Card date="Night" startTime="9:00 AM" endTime="4:00 AM">
            <Line label="Line 2"></Line>
          </Card>
        </div>
      </Content>
    </div>
  );
};

export default Operators;
