import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect } from "react";

const Home: NextPage = () => {
  const router = useRouter();
  useEffect(() => {
    router.push("/factory/operators");
  }, [""]);

  return (
    <>
      <Head>
        <title>Monitait</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
    </>
  );
};

export default Home;
