import Head from "next/head";
import React from "react";

const Integrations = () => {
  return (
    <div>
      <Head>
        <title>Monitait - Integrations</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Icon.png" />
      </Head>
      <div>Integrations Page</div>
    </div>
  );
};

export default Integrations;
