import Head from "next/head";
import React from "react";

const Reports = () => {
  return (
    <div>
      <Head>
        <title>Monitait - Reports</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Icon.png" />
      </Head>
      <div>
        Reports Page
      </div>
    </div>
  );
};

export default Reports;
