import Head from "next/head";
import React from "react";

const Support = () => {
  return (
    <div>
      <Head>
        <title>Monitait - Support</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/Icon.png" />
      </Head>
      <div>Support Page</div>
    </div>
  );
};

export default Support;
